export const COUNTRY_NAMES: Record<string, string> = {
  US: 'United States',
  GB: 'United Kingdom',
  FR: 'France',
  DE: 'Germany',
  IT: 'Italy',
  ES: 'Spain',
  CA: 'Canada',
  AU: 'Australia',
  JP: 'Japan',
  CN: 'China',
  IN: 'India',
  BR: 'Brazil',
  MX: 'Mexico',
  RU: 'Russia',
  KR: 'South Korea',
  AE: 'United Arab Emirates',
  SG: 'Singapore',
  HK: 'Hong Kong',
  NZ: 'New Zealand',
  IE: 'Ireland',
  NL: 'Netherlands',
  CH: 'Switzerland',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  PL: 'Poland',
  UA: 'Ukraine',
  AT: 'Austria',
  BE: 'Belgium',
  GR: 'Greece',
  PT: 'Portugal',
  CZ: 'Czech Republic',
  HU: 'Hungary',
  RO: 'Romania',
  IL: 'Israel',
  TH: 'Thailand',
  MY: 'Malaysia',
  ID: 'Indonesia',
  PH: 'Philippines',
  VN: 'Vietnam',
  EG: 'Egypt',
  ZA: 'South Africa',
  TR: 'Turkey',
  SA: 'Saudi Arabia',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Peru',
};

export const MAJOR_CITIES = new Set([
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'London',
  'Paris',
  'Tokyo',
  'Beijing',
  'Shanghai',
  'Mumbai',
  'Delhi',
  'Moscow',
  'São Paulo',
  'Sydney',
  'Melbourne',
  'Toronto',
  'Montreal',
  'Vancouver',
  'Mexico City',
  'Berlin',
  'Madrid',
  'Rome',
  'Barcelona',
  'Amsterdam',
  'Vienna',
  'Prague',
  'Stockholm',
  'Copenhagen',
  'Oslo',
  'Dubai',
  'Singapore',
  'Hong Kong',
  'Seoul',
  'Bangkok',
  'Jakarta',
  'Manila',
  'Cairo',
  'Istanbul',
  'Tel Aviv',
  'Cape Town',
  'Johannesburg',
  'Buenos Aires',
  'Rio de Janeiro',
  'Lima',
  'Bogotá',
  'Santiago',
  'Kyiv',
  'Warsaw',
  'Budapest',
  'Bucharest',
  'Athens',
  'Lisbon',
  'Dublin',
  'Edinburgh',
  'Manchester',
  'Birmingham',
  'Glasgow',
  'Liverpool',
  'Miami',
  'Boston',
  'Seattle',
  'San Francisco',
  'Las Vegas',
  'Portland',
  'Denver',
  'Atlanta',
  'Washington',
  'Baltimore',
  'New Orleans',
  'Austin',
  'Nashville',
  'Sacramento',
  'Oakland',
  'Minneapolis',
  'Milwaukee',
  'Cleveland',
  'Cincinnati',
  'Pittsburgh',
  'Detroit',
  'Indianapolis',
  'Columbus',
  'Charlotte',
  'Memphis',
  'Louisville',
  'Jacksonville',
  'Tampa',
  'Orlando',
  'St. Louis',
  'Kansas City',
  'Salt Lake City',
  'Raleigh',
  'Richmond',
  'Buffalo',
  'Hartford',
  'Birmingham',
  'Rochester',
  'Albany',
]);

export const POPULAR_CITIES_DISPLAY = [
  'New York',
  'London',
  'Tokyo',
  'Paris',
  'Los Angeles',
  'Sydney',
  'Dubai',
  'Singapore',
  'Hong Kong',
  'Berlin',
  'Toronto',
  'Amsterdam',
  'San Francisco',
  'Barcelona',
  'Rome',
];
