
export const UI_CONSTANTS = {
  SIDEBAR_DEBOUNCE_DELAY: 150,
  SEARCH_DEBOUNCE_DELAY: 300,
  BLUR_DELAY: 300,
  MAX_HISTORY_ITEMS: 10,
  MAX_RECENTLY_REMOVED_ITEMS: 5,
  THEME_TRANSITION_DURATION: 1000,
  MIN_SEARCH_LENGTH: 2,
  NIGHT_HOUR_START: 20,
  NIGHT_HOUR_END: 5,
  FORECAST_DAYS: 7,
} as const;
